Week_6/Day_2/auction/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get '/' => 'site#home'

  resources :users do
    resources :products do
      resources :reviews

    end
  end

  resources :users do
      resources :bids
  end

  resources :products do
      resources :bids
  end



end

Week_6/Day_2/auction/app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
  
end

Week_6/Day_2/auction/app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user
  has_many :bids
  has_many :reviews

  validates :minimum, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :deadline, presence: true

end

Week_6/Day_2/auction/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product
  belongs_to :user

 validates :description, presence: true

end

Week_6/Day_2/auction/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products
  has_many :bids
  has_many :reviews

  validates :email, uniqueness: true
  validates :email, presence: true


  def find_by_email(address)

    User.where(email: address).first

  end


end

Week_6/Day_2/auction/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

    
end

Week_6/Day_2/auction/app/controllers/bids_controller.rb
require 'pry'
class BidsController < ApplicationController

  def index
    @product = Product.find(params[:product_id])
    @bids = @product.bids.all.order(amount: :desc)
    @result = []
    @bids.each do |bid|
      @result << [ bid.amount, User.find(bid.user_id).name ]
      if @product.deadline < Date.today && @result.length == 1
        @result[0][1] = User.find(bid.user_id).name + " WINNER!!!" 
      end
    end
  end

  def new
    @bid = Bid.new
    @product = Product.find(params[:product_id])
  end


  def show
    @product = Product.find(params[:product_id])
    @bids = @product.bids.all
  end


  def create
    @product = Product.find(params[:product_id])
    @bid = @product.bids.new(bid_params)
    @user = User.find_by_email(params[:bid][:user_id])
    @bid.update_attributes(user_id: @user.id)

    if @product.deadline > Date.today 
      if @bid.amount >= @product.minimum
        if @bid.save
          redirect_to action: 'index'
        else
          render 'new'
        end
      else
      flash[:alert] = "Price minimum is #{@product.minimum}"
      render 'new'
      end
    else
      flash[:alert] = "Product no available"
      render 'new'
    end
  end


  private

  # def bid
  #   @_bid ||= bid.find(params[:bid_id])
  # end

  def bid_params
    params.require(:bid).permit(:amount )
  end


end

Week_6/Day_2/auction/app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @product = Product.new
  end

  def create
    @user = User.find(params[:user_id])
    @product = @user.products.new(product_params)

    if @product.save
      redirect_to action: 'index', controller: 'products'
    else
      render 'new'
    end
  end


  def index
    @products = Product.all
  end



  def edit
    @user = User.find(params[:user_id])
    @product = @user.products.find(params[:id])
  end


  def update
    @user = User.find(params[:user_id])
    @product = @user.products.find(params[:id])

    if @product.update_attributes(product_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end

  end


  def show
    @product = Product.find(params[:id])
    @bid = Bid.new
    @review = Review.new
  end


  private

  # def product
  #   @_product ||= product.find(params[:product_id])
  # end

  def product_params
    params.require(:product).permit(:title, :description, :deadline, :minimum )
  end

end

Week_6/Day_2/auction/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    # binding.pry
    @product = Product.find(params[:product_id])
    @review = @product.reviews.all

  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)

    if @review.save
      redirect_to action: 'index'

    else
      # render '/users/'+params[:user_id]+'/products/'+params[:id]
      # redirect_to action: 'show', controller: 'products'
      redirect_to user_product_path(current_user, @product)
    end

  end

  private

  def review_params
    params.require(:review).permit(:description)
  end
end

Week_6/Day_2/auction/app/controllers/site_controller.rb
class SiteController < ApplicationController


end

Week_6/Day_2/auction/app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!
    
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to action: 'index', controller: 'users'
    else
      render 'new'
    end
  end


  def index
    @users = User.all
  end


  def edit
    @user = User.find(params[:id])
  end


  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end

  end





  private

  # def user
  #   @_user ||= User.find(params[:user_id])
  # end

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

Week_6/Day_2/auction/app/helpers/application_helper.rb
module ApplicationHelper
end

Week_6/Day_2/auction/app/helpers/bids_helper.rb
module BidsHelper
end

Week_6/Day_2/auction/app/helpers/products_helper.rb
module ProductsHelper
end

Week_6/Day_2/auction/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Week_6/Day_2/auction/app/helpers/site_helper.rb
module SiteHelper
end

Week_6/Day_2/auction/app/helpers/users_helper.rb
module UsersHelper
end

Week_6/Day_2/auction/app/views/partials/_form.html.erb
<div id="top_bar">
<% if user_signed_in? %>
<p>Hello, <%=current_user.name %>.</p> 
  <p><%= link_to 'Sign out', destroy_user_session_path, method: 'DELETE' %></p>
<% else %>
  <p>
    <%= link_to 'No user yet? Sign_up', new_user_registration_path %> |
    <%= link_to 'Already a user? Sign_in! ', new_user_session_path %>
  </p>
<% end %>
</div>

Week_6/Day_2/auction/app/views/partials/_form_review.html.erb
<%= form_for [current_user, @product, @review] do |f| %>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit 'Save' %>

<% end %>

Week_6/Day_2/auction/app/views/products/edit.html.erb
<% if @product.errors.any? %>
    <ul>
      <% @product.errors.full_messages.each do |error| %>
        <li> <%= "#{error}" %> </li>
      <% end %>
    </ul>
<% end %>

<%= form_for  [@user, @product] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :deadline %>
  <%= f.date_field :deadline %>
  <br>
  <%= f.label :minimum %>
  <%= f.number_field :minimum %>
  <br>
  <%= f.submit 'Save' %>

<% end %>

<br>
<%= link_to("Cancel", user_products_path(@user)) %>

Week_6/Day_2/auction/app/views/products/index.html.erb
<h1><%= current_user.name %>´s All Products:</h1>
<ul>
  <% @products.each do |product| %>

    <li> <%= "#{product.title} - #{product.description} - #{product.deadline}" %>
    <%= link_to("Edit", edit_user_product_path(product.user_id, product)) %>
    <%= link_to("View", user_product_path(product.user_id, product)) %>

    </li>


  <% end %>
</ul>


<%= link_to("Back", "/") %>

Week_6/Day_2/auction/app/views/products/new.html.erb
<% if @product.errors.any? %>
    <ul>
      <% @product.errors.full_messages.each do |error| %>
        <li> <%= "#{error}" %> </li>
      <% end %>
    </ul>
<% end %>

<%= form_for  [@user, @product] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.label :deadline %>
  <%= f.date_field :deadline %>
  <br>
  <%= f.label :minimum %>
  <%= f.number_field :minimum %>
  <br>
  <%= f.submit 'Save' %>

<% end %>

<br>
<%= link_to("Cancel", user_products_path(@user)) %>

Week_6/Day_2/auction/app/views/products/show.html.erb
<h1>Details:</h1>

<h2><%= @product.title %></h2>
<h2><%= @product.description %></h2>
<h2><%= @product.deadline %></h2>

<%= render "partials/form_review"%>


<%= link_to("New Bid", new_product_bid_path(@product)) %>
<br>
<%= link_to("Actual Bids", product_bids_path(@product)) %>
<br>
<%= link_to("Back", products_path(@user)) %>

Week_6/Day_2/auction/app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li> <%= "#{error}" %> </li>
      <% end %>
    </ul>
<% end %>

<%= form_for  [@user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.submit 'Save' %>

<% end %>

<br>
<%= link_to("Cancel", users_path) %>

Week_6/Day_2/auction/app/views/users/index.html.erb
<h1>Users:</h1>
<ul>
  <% @users.each do |user| %>
    
    <li> <%= "#{user.name} - " %> <%= "#{user.email}" %>
    <%= link_to("Edit", edit_user_path(user)) %>  
    <%= link_to("Create Product", new_user_product_path(user)) %>  
    </li>


  <% end %>
</ul>



<%= link_to("Add new user", new_user_path) %>
<br>
<%= link_to("Home", "/") %>

Week_6/Day_2/auction/app/views/users/new.html.erb
<% if @user.errors.any? %>
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li> <%= "#{error}" %> </li>
      <% end %>
    </ul>
<% end %>

<%= form_for  [@user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.submit 'Save' %>

<% end %>

<br>
<%= link_to("Cancel", users_path) %>